//! Capture program for the conformance test-vector corpus.
//!
//! Per ADR-0004 the corpus vectors are generated by this `examples/`
//! program (so the OpenTelemetry SDK / prost crate dependency does not
//! pollute the harness's runtime build) and committed to the repository
//! under `tests/vectors/`. The runner walks the corpus on every CI run.
//!
//! Usage from the workspace root:
//!
//! ```sh
//! cargo run --example capture_corpus_vectors -p otlp-conformance-harness
//! ```
//!
//! The program is deterministic — running it twice produces the same
//! bytes — and idempotent: it overwrites existing vectors with the same
//! content. The `source` field in each `.expected.json` records the
//! capture date and program revision so reviewers can audit drift.

use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::{Path, PathBuf};

use prost::Message;

use opentelemetry_proto::tonic::collector::logs::v1::ExportLogsServiceRequest;
use opentelemetry_proto::tonic::collector::metrics::v1::ExportMetricsServiceRequest;
use opentelemetry_proto::tonic::collector::trace::v1::ExportTraceServiceRequest;
use opentelemetry_proto::tonic::common::v1::{any_value, AnyValue, InstrumentationScope, KeyValue};
use opentelemetry_proto::tonic::logs::v1::{LogRecord, ResourceLogs, ScopeLogs};
use opentelemetry_proto::tonic::metrics::v1::{
    metric::Data as MetricData, number_data_point, Gauge, Metric, NumberDataPoint, ResourceMetrics,
    ScopeMetrics, Sum,
};
use opentelemetry_proto::tonic::resource::v1::Resource;
use opentelemetry_proto::tonic::trace::v1::{ResourceSpans, ScopeSpans, Span};

const CAPTURE_DATE: &str = "2026-05-03";
const SDK_NOTE: &str = "encoded via prost from opentelemetry-proto =0.27.0 fixtures";
const SPEC_VERSION: &str = "1.5.0";

fn main() {
    let root = vectors_root();
    println!("Writing corpus vectors under {}", root.display());

    // Accept vectors (one per signal).
    let logs_bytes = encode_minimal_logs();
    write_vector(
        &root.join("logs/accept/minimal.bin"),
        &logs_bytes,
        accept_descriptor(
            "logs",
            "opentelemetry_proto::tonic::collector::logs::v1::ExportLogsServiceRequest",
            "Minimal logs export request — one resource (service.name), one scope, one log record. Source: capture_corpus_vectors.rs.",
        ),
    );

    let traces_bytes = encode_minimal_traces();
    write_vector(
        &root.join("traces/accept/minimal.bin"),
        &traces_bytes,
        accept_descriptor(
            "traces",
            "opentelemetry_proto::tonic::collector::trace::v1::ExportTraceServiceRequest",
            "Minimal traces export request — one resource, one scope, one INTERNAL span. Source: capture_corpus_vectors.rs.",
        ),
    );

    let metrics_bytes = encode_minimal_metrics();
    write_vector(
        &root.join("metrics/accept/minimal.bin"),
        &metrics_bytes,
        accept_descriptor(
            "metrics",
            "opentelemetry_proto::tonic::collector::metrics::v1::ExportMetricsServiceRequest",
            "Minimal metrics export request — one resource, one scope, one sum and one gauge. Source: capture_corpus_vectors.rs.",
        ),
    );

    // Reject vectors — empty input (one per signal).
    for signal in ["logs", "traces", "metrics"] {
        write_vector(
            &root.join(format!("{signal}/reject/empty.bin")),
            &[],
            reject_descriptor_simple(
                signal,
                "EmptyInput",
                "Hand-crafted: 0-byte file representing the simplest empty-body case.",
            ),
        );
    }

    // Reject vectors — malformed protobuf for logs (truncated, bad_varint, bad_tag).
    let truncated = truncate(&logs_bytes, 50);
    write_vector(
        &root.join("logs/reject/truncated.bin"),
        &truncated,
        reject_descriptor_simple(
            "logs",
            "WireType.ProtobufDecode",
            "logs/accept/minimal.bin truncated at byte 50.",
        ),
    );
    write_vector(
        &root.join("logs/reject/bad_varint.bin"),
        &bad_varint(),
        reject_descriptor_simple(
            "logs",
            "WireType.ProtobufDecode",
            "Tag byte 0x08 (field 1, varint) followed by nine continuation bytes. Hand-crafted.",
        ),
    );
    write_vector(
        &root.join("logs/reject/bad_tag.bin"),
        &bad_tag(),
        reject_descriptor_simple(
            "logs",
            "WireType.ProtobufDecode",
            "Tag references undefined field 99999 (wire type 2) on ExportLogsServiceRequest. Hand-crafted.",
        ),
    );

    // Reject vectors — malformed protobuf for traces and metrics.
    write_vector(
        &root.join("traces/reject/bad_varint.bin"),
        &bad_varint(),
        reject_descriptor_simple(
            "traces",
            "WireType.ProtobufDecode",
            "Same bad-varint sequence as logs/reject/bad_varint.bin; asserted as traces.",
        ),
    );
    write_vector(
        &root.join("metrics/reject/bad_varint.bin"),
        &bad_varint(),
        reject_descriptor_simple(
            "metrics",
            "WireType.ProtobufDecode",
            "Same bad-varint sequence as logs/reject/bad_varint.bin; asserted as metrics.",
        ),
    );

    // Reject vectors — signal mismatch.
    write_vector(
        &root.join("logs/reject/traces_misrouted.bin"),
        &traces_bytes,
        signal_mismatch_descriptor("logs", "traces"),
    );
    write_vector(
        &root.join("logs/reject/metrics_misrouted.bin"),
        &metrics_bytes,
        signal_mismatch_descriptor("logs", "metrics"),
    );
    write_vector(
        &root.join("traces/reject/logs_misrouted.bin"),
        &logs_bytes,
        signal_mismatch_descriptor("traces", "logs"),
    );
    write_vector(
        &root.join("traces/reject/metrics_misrouted.bin"),
        &metrics_bytes,
        signal_mismatch_descriptor("traces", "metrics"),
    );
    write_vector(
        &root.join("metrics/reject/logs_misrouted.bin"),
        &logs_bytes,
        signal_mismatch_descriptor("metrics", "logs"),
    );
    write_vector(
        &root.join("metrics/reject/traces_misrouted.bin"),
        &traces_bytes,
        signal_mismatch_descriptor("metrics", "traces"),
    );

    println!("Corpus written.");
}

fn vectors_root() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests");
    p.push("vectors");
    p
}

fn write_vector(path: &Path, bytes: &[u8], descriptor: serde_json::Value) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create parent");
    }
    fs::write(path, bytes).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    let mut desc = descriptor;
    let hash = sha256_hex(bytes);
    if let Some(obj) = desc.as_object_mut() {
        obj.insert(
            "content_hash".to_string(),
            serde_json::Value::String(format!("sha256:{hash}")),
        );
    }
    let json_path = path.with_extension("expected.json");
    let json_text = serde_json::to_string_pretty(&desc).expect("serialise descriptor");
    fs::write(&json_path, format!("{json_text}\n"))
        .unwrap_or_else(|e| panic!("write {}: {e}", json_path.display()));
}

fn accept_descriptor(signal: &str, type_path: &str, source: &str) -> serde_json::Value {
    serde_json::json!({
        "schema_version": 1,
        "asserted_signal": signal,
        "asserted_framing": "HttpProtobuf",
        "expected_verdict": {
            "accept": { "type_path": type_path }
        },
        "spec_version": SPEC_VERSION,
        "source": format!("{source} Captured {CAPTURE_DATE}. {SDK_NOTE}.")
    })
}

fn reject_descriptor_simple(signal: &str, rule: &str, source: &str) -> serde_json::Value {
    let rule_value = match rule {
        "EmptyInput" => serde_json::json!("EmptyInput"),
        "WireType.ProtobufDecode" => serde_json::json!({
            "WireType": "ProtobufDecode"
        }),
        other => panic!("unsupported simple rule {other}"),
    };
    serde_json::json!({
        "schema_version": 1,
        "asserted_signal": signal,
        "asserted_framing": "HttpProtobuf",
        "expected_verdict": {
            "reject": { "rule": rule_value }
        },
        "spec_version": SPEC_VERSION,
        "source": format!("{source} Captured {CAPTURE_DATE}.")
    })
}

fn signal_mismatch_descriptor(asserted: &str, observed: &str) -> serde_json::Value {
    serde_json::json!({
        "schema_version": 1,
        "asserted_signal": asserted,
        "asserted_framing": "HttpProtobuf",
        "expected_verdict": {
            "reject": {
                "rule": {
                    "WireType": {
                        "SignalMismatch": {
                            "observed": observed,
                            "asserted": asserted,
                        }
                    }
                }
            }
        },
        "spec_version": SPEC_VERSION,
        "source": format!(
            "{observed}/accept/minimal.bin bytes routed to {asserted} for SignalMismatch coverage. Captured {CAPTURE_DATE}."
        ),
    })
}

fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut s = String::with_capacity(64);
    for b in digest {
        let _ = FmtWrite::write_fmt(&mut s, format_args!("{b:02x}"));
    }
    s
}

// ---- byte synthesis (mirrors tests/common/mod.rs to keep the example
// self-contained; small intentional duplication) ----

fn encode_minimal_logs() -> Vec<u8> {
    let req = ExportLogsServiceRequest {
        resource_logs: vec![ResourceLogs {
            resource: Some(Resource {
                attributes: vec![string_kv("service.name", "kaleidoscope-corpus-fixture")],
                dropped_attributes_count: 0,
            }),
            scope_logs: vec![ScopeLogs {
                scope: Some(InstrumentationScope {
                    name: "kaleidoscope.test".to_string(),
                    version: "0.0.0".to_string(),
                    attributes: vec![],
                    dropped_attributes_count: 0,
                }),
                log_records: vec![LogRecord {
                    time_unix_nano: 1_700_000_000_000_000_000,
                    observed_time_unix_nano: 1_700_000_000_000_000_000,
                    severity_number: 9,
                    severity_text: "INFO".to_string(),
                    body: Some(AnyValue {
                        value: Some(any_value::Value::StringValue(
                            "minimal log record for corpus".to_string(),
                        )),
                    }),
                    attributes: vec![],
                    dropped_attributes_count: 0,
                    flags: 0,
                    trace_id: vec![],
                    span_id: vec![],
                }],
                schema_url: String::new(),
            }],
            schema_url: String::new(),
        }],
    };
    req.encode_to_vec()
}

fn encode_minimal_traces() -> Vec<u8> {
    let req = ExportTraceServiceRequest {
        resource_spans: vec![ResourceSpans {
            resource: Some(Resource {
                attributes: vec![string_kv("service.name", "kaleidoscope-corpus-fixture")],
                dropped_attributes_count: 0,
            }),
            scope_spans: vec![ScopeSpans {
                scope: Some(InstrumentationScope {
                    name: "kaleidoscope.test".to_string(),
                    version: "0.0.0".to_string(),
                    attributes: vec![],
                    dropped_attributes_count: 0,
                }),
                spans: vec![Span {
                    trace_id: vec![1; 16],
                    span_id: vec![1; 8],
                    trace_state: String::new(),
                    parent_span_id: vec![],
                    flags: 0,
                    name: "minimal-span".to_string(),
                    kind: 1,
                    start_time_unix_nano: 1_700_000_000_000_000_000,
                    end_time_unix_nano: 1_700_000_000_000_000_010,
                    attributes: vec![],
                    dropped_attributes_count: 0,
                    events: vec![],
                    dropped_events_count: 0,
                    links: vec![],
                    dropped_links_count: 0,
                    status: None,
                }],
                schema_url: String::new(),
            }],
            schema_url: String::new(),
        }],
    };
    req.encode_to_vec()
}

fn encode_minimal_metrics() -> Vec<u8> {
    let resource = Resource {
        attributes: vec![string_kv("service.name", "kaleidoscope-corpus-fixture")],
        dropped_attributes_count: 0,
    };
    let scope = InstrumentationScope {
        name: "kaleidoscope.test".to_string(),
        version: "0.0.0".to_string(),
        attributes: vec![],
        dropped_attributes_count: 0,
    };
    let req = ExportMetricsServiceRequest {
        resource_metrics: vec![ResourceMetrics {
            resource: Some(resource),
            scope_metrics: vec![ScopeMetrics {
                scope: Some(scope),
                metrics: vec![
                    Metric {
                        name: "request_count".to_string(),
                        description: "minimal sum metric".to_string(),
                        unit: "1".to_string(),
                        metadata: vec![],
                        data: Some(MetricData::Sum(Sum {
                            data_points: vec![NumberDataPoint {
                                attributes: vec![],
                                start_time_unix_nano: 1_700_000_000_000_000_000,
                                time_unix_nano: 1_700_000_000_000_000_010,
                                exemplars: vec![],
                                flags: 0,
                                value: Some(number_data_point::Value::AsInt(42)),
                            }],
                            aggregation_temporality: 2,
                            is_monotonic: true,
                        })),
                    },
                    Metric {
                        name: "current_temperature".to_string(),
                        description: "minimal gauge metric".to_string(),
                        unit: "Cel".to_string(),
                        metadata: vec![],
                        data: Some(MetricData::Gauge(Gauge {
                            data_points: vec![NumberDataPoint {
                                attributes: vec![],
                                start_time_unix_nano: 1_700_000_000_000_000_000,
                                time_unix_nano: 1_700_000_000_000_000_010,
                                exemplars: vec![],
                                flags: 0,
                                value: Some(number_data_point::Value::AsDouble(21.5)),
                            }],
                        })),
                    },
                ],
                schema_url: String::new(),
            }],
            schema_url: String::new(),
        }],
    };
    req.encode_to_vec()
}

fn string_kv(key: &str, value: &str) -> KeyValue {
    KeyValue {
        key: key.to_string(),
        value: Some(AnyValue {
            value: Some(any_value::Value::StringValue(value.to_string())),
        }),
    }
}

fn truncate(bytes: &[u8], at: usize) -> Vec<u8> {
    let cut = at.min(bytes.len());
    bytes[..cut].to_vec()
}

fn bad_varint() -> Vec<u8> {
    vec![0x08, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80]
}

fn bad_tag() -> Vec<u8> {
    let mut v = Vec::new();
    let mut n: u64 = (99999u64 << 3) | 2;
    while n >= 0x80 {
        v.push(((n & 0x7F) | 0x80) as u8);
        n >>= 7;
    }
    v.push(n as u8);
    v.push(5);
    v.extend_from_slice(&[0xFF, 0xFE, 0xFD, 0xFC, 0xFB]);
    v
}
